### ISSUE TITLE
Add a keyboard shortcut to take screenshot

### ISSUE THREAD

**Issue by Gitoffthelawn** [stefansundin/one-click-screenshot#1]
Great idea.

Can you add a user-configurable keyboard shortcut to take the screenshot?

Can just use a pref to specify which key combination if you want to keep it ultra-simple.

**Comment by Gitoffthelawn** [comment]
Thanks!  BTW, Nimbus Screen Capture (the antithesis of your extension!) is very flexible in this regard, if you want to take a look.

**Comment by stefansundin** [comment]
A keyboard shortcut will be added to the next version. By default the shortcut is Alt+Shift+S.

**Comment by Gitoffthelawn** [comment]
Great!  Thanks!

**Comment by Gitoffthelawn** [comment]
Just for reference, it looks like the default shortcut is Alt+Shift+W in Firefox.

Can you add a way to change that, even if it's just an about:config pref?

Also, the shortcut isn't doing anything right now, but it might be because the extension isn't working at all for me.

**Comment by stefansundin** [comment]
I was originally planning to use Alt+Shift+S on Firefox too, but it conflicted with opening the history menu (try pressing Alt+S). What happened is that the history menu opened and the screenshot procedure started, and I don't know how to override that behavior. So I decided to switch the shortcut.

There is no way to change the default shortcut for webextensions in Firefox. The easiest way for you to experiment with it is to download the source code and load it in `about:debugging`. If you can find a way to improve it, let me know.

When I first loaded the extension, I noticed that I had to reload tabs to get the shortcut to work in that tab. Not sure why it happened.

**Comment by Gitoffthelawn** [comment]
Thanks for the feedback.

In regards to not changing the shortcut, that is going to cause an issue with many extensions!

Perhaps you can file a bugzilla report so that Mozilla knows it's an issue.

BTW, in your description on AMO, you might want to include the fact that this is a *webextensions* extension.  They are the "hot" thing right now, and it might draw more interest from the community.
