### ISSUE TITLE
How to use it and compile it under windows ?

### ISSUE THREAD

**Issue by miranos** [stefansundin/one-click-screenshot#4]
Hi
How to compile the extension under windows and use it on firefox and chrome please ?

Thanks for this great work.

**Comment by stefansundin** [comment]
The JavaScript is written in CoffeScript, so you need a coffeescript compiler, I use the one from npm: https://www.npmjs.com/package/coffee-script

You can also copy and paste it on this website: http://coffeescript.org/#try:alert%20%22paste%20code%20here%22

You also need to download the bootstrap css (look in bootstrap.sh).

**Comment by stefansundin** [comment]
The next version will no longer use CoffeeScript.
